// Thailand deck copy. No em dashes anywhere. No other markets mentioned.
const YTWA = 'Google, YouTube Works Awards Thailand 2026, via The Story Thailand and Telecomlover (25 Sep 2026)';
module.exports = {
  market: 'Thailand',
  file: 'YouTube_Trending_Content_Pack_2026_TH.pptx',
  cover: {
    kicker: 'YOUTUBE ADVERTISING 2026 · THAILAND',
    line1: 'Capture the Culture.',
    line2: 'Capitalise on the Trend.',
    sub: 'YouTube Trending Content Pack 2026 · Thailand',
    notes: 'YouTube Trending Content Pack 2026 for Thailand. Six content pillars built from public Google and YouTube announcements (YouTube Works Awards Thailand 2026, Year in Search 2025, YouTube year-end lists), local press, chart and box office data, and Social Blade subscriber counts (September 2026). Every stat slide carries its source in the footer; details are in the speaker notes.',
  },
  why: {
    title: 'On YouTube, Thai content keeps working',
    sub: 'Longevity, scale, trust and return, on one platform',
    source: 'Source: ' + YTWA + '; Bangkok Post (2025); Analytic Edge MMM meta-analysis (2021-2025, 23 Thai studies)',
    tiles: [
      { label: 'LONGEVITY', icon: 'PiInfinityBold', big: '40%', text: 'of video views in Thailand happen more than one month after upload' },
      { label: 'SCALE', icon: 'PiUsersThreeBold', big: '1,300', text: 'Thai channels have more than 1 million subscribers each' },
      { label: 'TRUST', icon: 'PiThumbsUpBold', big: '90%', text: 'of Thai users rate YouTube the most trustworthy video platform' },
      { label: 'RETURN', icon: 'PiChartLineUpBold', big: '1.71x', text: 'higher marketing ROI from YouTube than traditional TV' },
    ],
    notes: 'LONGEVITY 40%: Google at YouTube Works Awards Thailand 2026 (reported 25 Sep 2026 by The Story Thailand and Telecomlover): 40% of video views occur more than one month after upload.\nSCALE 1,300: "Roughly 1,300 Thailand-based YouTube channels have more than 1 million subscribers each" (Bangkok Post, 2025). Google also reported 90,000+ Thai channels with 10,000+ subscribers (YouTube data, Dec 2025).\nTRUST 90%: Google & Kantar, May 2026, cited at YouTube Works Awards Thailand 2026.\nRETURN 1.71x: Analytic Edge MMM meta-analysis, 2021-2025, 23 Thai studies: YouTube ROI 1.71x traditional TV and 1.51x the average of other media (The Story Thailand, 25 Sep 2026).',
  },
  screens: {
    title: 'Thailand watches YouTube on every screen',
    sub: 'Living-room TV, long-form, Shorts and live',
    source: 'Source: ' + YTWA + '; Google via RAiNMaker (18 Jun 2026); Esports Charts (RoV Pro League 2026 Summer)',
    tiles: [
      { label: 'CONNECTED TV', icon: 'PiTelevisionBold', big: '75%', text: 'of travel creator Go Went Go\'s views come from the TV screen' },
      { label: 'LONG-FORM', icon: 'PiMicrophoneBold', big: '+50%', text: 'year-on-year growth in podcast viewing on YouTube in Thailand' },
      { label: 'SHORTS', icon: 'PiDeviceMobileBold', big: '+85%', text: 'year-on-year growth in YouTube Shorts uploads in Thailand' },
      { label: 'LIVE', icon: 'PiBroadcastBold', big: '122K', text: 'peak live viewers for RoV Pro League 2026 Summer' },
    ],
    notes: 'CONNECTED TV 75%: Google featured Go Went Go at YouTube Works Awards Thailand 2026: 75% of the channel\'s viewing is on the TV screen (The Story Thailand, 25 Sep 2026). Nielsen has offered deduplicated YouTube CTV campaign measurement in Thailand since 23 Oct 2024.\nLONG-FORM +50%: podcast viewing on YouTube Thailand grew over 50% in June 2025 vs the prior year (Google data via RAiNMaker, 18 Jun 2026).\nSHORTS +85%: YouTube Shorts uploads grew 85% year on year (Google, 25 Sep 2026).\nLIVE 122K: Esports Charts, RoV Pro League 2026 Summer peak viewers (all platforms).',
  },
  contents: {
    title: 'Six things Thailand can\'t stop watching',
    notes: 'Six pillars chosen from public data: YouTube year-end lists 2025 (top music videos, top creators), Google Year in Search 2025 Thailand, YouTube Works Awards Thailand 2026, Social Blade and HypeAuditor channel rankings, box office and esports data. Kids-directed channels and creators with controversies were screened out.',
  },
  pillars: [
    // ============================================================ 01 SERIES
    {
      key: 'series', art: 'tele', num: '01', name: 'Series Nation', tag: '01 · SERIES NATION',
      short: 'Lakorn, BL series and variety, streamed like prime time', icon: 'PiTelevisionSimpleBold',
      banner: ['PiTelevisionSimpleBold', 'PiHeartBold', 'PiFilmSlateBold', 'PiPopcornBold'],
      hero: { topChip: ['Live now', 'PiBroadcastBold'], botChip: ['New episode', 'PiPlayBold'], dur: '46:20' },
      divider: { kicker: 'THE PULL OF', desc: 'Lakorn, BL series and variety shows: Thailand\'s TV now lives on YouTube, live, on demand and on the family TV.' },
      fact: {
        icon: 'PiCrownBold', big: 'Top 3', lead: 'Thailand\'s three most-subscribed YouTube channels are TV channels, not creators',
        text: 'one31 (45.1M), Workpoint (44M) and Ch3 (37M) lead the whole country on YouTube.',
        sowhat: 'Thai families made YouTube their TV guide. Brands can buy prime-time attention inside the shows people already watch.',
        source: 'Source: Social Blade, Thailand channel ranks (Sep 2026)',
        notes: 'Social Blade (checked Sep 2026): ช่อง one31 45.1M subscribers, Thailand rank #1 (36.0B views); WorkpointOfficial 44M, rank #2 (44.7B views); Ch3Thailand 37M, rank #3 (26.5B views). HypeAuditor\'s Thailand ranking (Sep 2026) shows the same top 3.',
      },
      insight: {
        type: 'bars',
        title: 'Thai TV is YouTube\'s biggest show',
        sub: 'Networks and series studios lead the country',
        chartLabel: 'Subscribers, millions (Social Blade, Sep 2026)',
        bars: [['one31', 45.1, '45.1M'], ['Workpoint', 44, '44M'], ['Ch3Thailand', 37, '37M'], ['GMMTV', 20.9, '20.9M'], ['Ch7HD', 19.7, '19.7M']],
        source: 'Source: Social Blade (Sep 2026); Nation Thailand (5 Jun 2026); The Geekiary (Nov 2025)',
        stats: [
          { big: '฿4.9B+', text: 'BL and GL series industry in 2025, growing about 17% a year' },
          { big: '38', text: 'new series announced at GMMTV\'s 2026 lineup event, a record' },
          { big: '44.7B', text: 'lifetime views on Workpoint\'s channel of variety and game shows' },
        ],
      },
      insightNotes: 'Subscribers (Social Blade, Sep 2026): one31 45.1M, WorkpointOfficial 44M, Ch3Thailand 37M, GMMTV OFFICIAL 20.9M (20.2B views), Ch7HD 19.7M.\nBL/GL industry: forecast to exceed 4.9 billion baht in 2025 with ~17% average annual growth; GMMTV 2024 revenue 2.463B baht (Nation Thailand, 5 Jun 2026).\nGMMTV 2026 lineup event on 25 Nov 2025 announced a record 38 series across BL, GL and other genres (The Geekiary, Nov 2025).\nWorkpoint lifetime views 44.7B (Social Blade).\nGoogle Year in Search 2025 Thailand: Thai series dominated the drama list (#1 สงคราม ส่งด่วน, #2 คุณพี่เจ้าขาดิฉันเป็นห่านมิใช่หงส์, #3 เขมจิราต้องรอด).',
      working: {
        title: 'Every episode, every clip, every screen',
        source: 'Source: Social Blade (Sep 2026); Google Year in Search Thailand (4 Dec 2025); The Geekiary (Nov 2025)',
        formats: [
          { icon: 'PiTelevisionBold', t: 'Full episodes', d: 'Catch-up lakorn and series on the living-room TV' },
          { icon: 'PiFilmSlateBold', t: 'Highlights & scenes', d: 'The scene everyone talks about, cut short and shared' },
          { icon: 'PiHeartBold', t: 'BL & GL fandom', d: 'Behind the scenes, fan meets and couple content' },
          { icon: 'PiMicrophoneStageBold', t: 'Variety & game shows', d: 'Workpoint-style formats built for daily viewing' },
        ],
        moments: [
          { d: 'LATE NOV 2026', t: 'GMMTV\'s annual lineup reveal for 2027 series' },
          { d: 'Q4 2026', t: 'New prime-time lakorn season across the networks' },
          { d: '31 DEC 2026', t: 'New Year countdown specials' },
          { d: 'ALWAYS-ON', t: 'Daily episodes and clips uploaded after broadcast' },
        ],
      },
      workingNotes: 'GMMTV held its 2026 lineup event on 25 Nov 2025 (The Geekiary); the date of the 2027 event is not yet announced, so "late Nov" reflects past timing. Networks upload full episodes and highlights daily; one31 has uploaded 214,000+ videos (Social Blade).',
      fit: {
        source: 'Source: Nation Thailand (5 Jun 2026); YouTube Works Awards Thailand 2026 winners via Marketing Oops (24 Sep 2026)',
        cats: [
          { icon: 'PiHouseBold', t: 'FMCG & Household', d: 'Dettol\'s "It\'s Dettol Time" was Best of Thailand 2026' },
          { icon: 'PiSparkleBold', t: 'Beauty & Skincare', d: 'The lead\'s look, the next morning' },
          { icon: 'PiWifiHighBold', t: 'Telco & Devices', d: 'Stream every episode, on every screen' },
          { icon: 'PiBankBold', t: 'Banking & Insurance', d: 'Family stories are future stories' },
        ],
        join: [
          { t: 'In-series placement', d: 'Your product in the story, in the cast\'s voice' },
          { t: 'Fandom partner', d: 'Fan meets, behind the scenes and couple content' },
          { t: 'Highlights Roadblock', d: 'Own every clip of the week\'s big episode' },
        ],
      },
      fitNotes: 'Best of Thailand 2026: Dettol "It\'s Dettol Time" (SOUR Bangkok, Phenomena). Y-series fan clubs fund their own ads on public transport and outdoor media (Nation Thailand, 5 Jun 2026), which shows how actively BL fandoms engage with brands.',
      creators: {
        title: 'Creators: series & TV', sub: 'Networks and series studios',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'one31', s: '45.1M', x: 'Lakorn', i: 'O31', url: 'UC8f7MkX4MFOOJ2SerXLInCA' },
          { n: 'WorkpointOfficial', s: '44M', x: 'Variety', i: 'WP', url: 'UC3ZkCd7XtUREnjjt3cyY_gg' },
          { n: 'Ch3Thailand', s: '37M', x: 'Lakorn', i: 'CH3', url: 'UC48h7Dst_hX82HxOf3xJw_w' },
          { n: 'GMMTV OFFICIAL', s: '20.9M', x: 'BL & series', i: 'GM', url: 'UC8BzJM6_VbZTdiNLD4R1jxQ' },
          { n: 'Ch7HD', s: '19.7M', x: 'Lakorn', i: 'CH7', url: 'UCXUVnTEsLZBim_WlWxBvEwA' },
          { n: 'Thai Ch8', s: '17.7M', x: 'Lakorn', i: 'CH8', url: 'UCtBu8Wb2BUoduUXJS9Uss7Q' },
          { n: 'GMM25Thailand', s: '16.4M', x: 'Series', i: '25', url: 'UCTP5z0kFg6-nPcZ79gTC67Q' },
          { n: 'ZENSE MORE', s: '8.38M', x: 'Variety', i: 'ZM', url: 'UCyw69lFs9nFatEft6isn1CA' },
          { n: 'GDH', s: '1.73M', x: 'Films', i: 'GDH', url: 'UC_rENyV7n1gtp6pPKpvuXGg' },
        ],
      },
      ideas: {
        title: 'Put your brand inside the story',
        cards: [
          { icon: 'PiFilmSlateBold', t: 'Behind the lakorn', c: 'one31', d: 'a backstage mini-series from the set, with the brand as the cast\'s on-set essential' },
          { icon: 'PiStarBold', t: 'Celebrity show integration', c: 'WorkpointOfficial', d: 'a branded game, prize or mission segment inside a star-studded variety show' },
          { icon: 'PiHeartBold', t: 'BL couple challenge', c: 'GMMTV OFFICIAL', d: 'series stars play a brand game between episodes, cut for fans' },
          { icon: 'PiTelevisionBold', t: 'Finale watch party', c: 'Ch3Thailand', d: 'a live pre-show and recap around a big lakorn finale, hosted by the brand' },
        ],
        band: [
          { t: 'Show segment sponsor', d: 'Title, segment or mission sponsor inside the show' },
          { t: 'Fandom content series', d: '3 to 5 behind-the-scenes and couple episodes' },
          { t: 'Clips to Shorts', d: 'The week\'s big scene cut into Shorts and boosted' },
        ],
      },
      inMarket: 'FMCG and household, beauty and skincare, telco and devices, banking and insurance',
      lineups: [
        { t: 'VELOTREND: THAI LAKORN & SERIES', d: 'Trending episodes, clips and highlights' },
        { t: 'VELOTREND: BL & GL FANDOM', d: 'Series scenes, fan meets and couple content' },
      ],
      what: 'series & TV',
    },
    // ============================================================ 02 MUSIC
    {
      key: 'music', art: 'opm', num: '02', name: 'Luk Thung x Rap', tag: '02 · LUK THUNG X RAP',
      short: 'Country roots meet rap, and every top hit is Thai', icon: 'PiMusicNotesBold',
      banner: ['PiMusicNotesBold', 'PiMicrophoneStageBold', 'PiGuitarBold', 'PiTicketBold'],
      hero: { topChip: ['Sold out', 'PiTicketBold'], botChip: ['Trending', 'PiFireBold'], dur: '4:05' },
      divider: { kicker: 'THE SOUND OF', desc: 'Luk thung and mor lam met rap, and Thai artists took every spot on YouTube\'s music chart.' },
      fact: {
        icon: 'PiMicrophoneStageBold', big: '554M', lead: 'Thailand\'s #1 artist on YouTube in 2024 was a 51-year-old mor lam singer',
        text: 'Monkaen Kaenkoon, from Yasothon in Isan, beat every pop and rap act with 554 million views.',
        sowhat: 'Country music is not niche here. Brands that speak Isan and luk thung reach the biggest music audience in the country.',
        source: 'Source: YouTube Charts Thailand 2024 via Nation Thailand (11 Jan 2025)',
        notes: 'YouTube Charts Thailand 2024 (data 7 Jan 2024 to 7 Jan 2025), reported by Nation Thailand on 11 Jan 2025: #1 Monkaen Kaenkoon (mor lam / Isan) 554M views; #2 SARAN (rap) 420M; #3 Supakan "Book" Pranot (luk thung) 403M; #4 ILLSLICK 402M; #5 Silly Fools 397M. Monkaen, 51, from Yasothon, also led in 2020.',
      },
      insight: {
        type: 'stats',
        title: 'Every top music video in Thailand is Thai',
        sub: 'Rap, luk thung and mor lam lead the charts',
        source: 'Source: YouTube Thailand year-end lists (4 Dec 2025); Social Blade (Sep 2026); ' + YTWA,
        stats: [
          { icon: 'PiYoutubeLogoBold', big: '10 of 10', text: 'top music videos of 2025 were Thai, led by rap x luk thung "Kularb"' },
          { icon: 'PiMusicNotesBold', big: '22.3M', text: 'subscribers for Grammy Gold, a luk thung label channel' },
          { icon: 'PiPlayBold', big: '27M+', text: 'views for Kradaeng Arsayam\'s "Bangkok City", spotlighted by Google in 2026' },
        ],
        why: 'the hit is only the start. Live cuts, covers, dance Shorts and festival clips keep songs climbing for months, from Bangkok to Isan, on phone and TV.',
      },
      insightNotes: 'YouTube Thailand top music videos 2025 (Google Thailand blog, 4 Dec 2025): 1 กุหลาบ (KULARB) F.HERO ft. ก้านตอง ทุ่งเงิน x SARAN; 2 ที่คั่นหนังสือ BOWKYLION ft. NONT TANONT; 3 ตีหนึ่งที่คูเมือง ILLSLICK; 4 ดิด คิตตี้; 5 ปลายฟ้า BLE PATUMRACH x แมน ภิสิทธิ์พงษ์; 6 and 9 LITTLE JOHN; 7 ไปรยา KRK; 8 and 10 YOUNGOHM. Google noted a blend of rap and luk thung and Thai artists in all 10 positions.\nGRAMMY GOLD OFFICIAL 22.3M subscribers, 28.6B views (Social Blade, Sep 2026).\n"Bangkok City" by Kradaeng Arsayam passed 27M views on Vevo, cited by Google at YouTube Works Awards Thailand 2026.',
      working: {
        title: 'Fans don\'t just listen. They sing, dance and join in',
        source: 'Source: YouTube Thailand year-end lists (4 Dec 2025); ChaPop (29 Jul 2026); outthailand.com (Loy Krathong 2026)',
        formats: [
          { icon: 'PiMonitorPlayBold', t: 'Music videos', d: 'Story-driven MVs that climb the year-end charts' },
          { icon: 'PiMicrophoneStageBold', t: 'Live & festival cuts', d: 'Stage moments from concerts and temple fairs' },
          { icon: 'PiDeviceMobileBold', t: 'Dance & cover Shorts', d: 'Fans film the hook and pass it on' },
          { icon: 'PiUsersThreeBold', t: 'Collabs & features', d: 'Rap x luk thung features that cross fanbases' },
        ],
        moments: [
          { d: '24 NOV 2026', t: 'Loy Krathong: festival songs and live stages' },
          { d: '12 TO 13 DEC 2026', t: 'Big Mountain music festival, Khao Yai' },
          { d: 'DEC 2026', t: 'Year-end charts and recap season' },
          { d: '13 TO 15 APR 2027', t: 'Songkran: the biggest party season of the year' },
        ],
      },
      workingNotes: 'Big Mountain Music Festival 2026 ("Big Mountain Village"), 12 to 13 Dec 2026 at Chokchai Village 3, organized by GMM Show (ChaPop, 29 Jul 2026). Loy Krathong 2026 falls on 24 Nov 2026 (outthailand.com and others). Songkran is 13 to 15 April. YouTube published its 2025 year-end lists on 4 Dec 2025.',
      fit: {
        source: 'Source: YouTube Works Awards Thailand 2026 winners via Marketing Oops (24 Sep 2026)',
        cats: [
          { icon: 'PiCoffeeBold', t: 'Beverages & Snacks', d: 'Snack Jack won The Big Bang 2026 on YouTube' },
          { icon: 'PiDeviceMobileBold', t: 'Mobile & Telco', d: 'vivo V70 won Multiformat Storytelling 2026' },
          { icon: 'PiMotorcycleBold', t: 'Motorbikes & Auto', d: 'The ride home to Isan for the festival' },
          { icon: 'PiWalletBold', t: 'E-wallets & Banking', d: 'Tickets, merch and festival spending' },
        ],
        join: [
          { t: 'Artist feature', d: 'A brand-backed collab track or live session' },
          { t: 'Festival partner', d: 'Own the stage cuts from Loy Krathong to Songkran' },
          { t: 'Cover challenge', d: 'Fans cover the hook in Shorts, boosted as ads' },
        ],
      },
      fitNotes: 'YouTube Works Awards Thailand 2026 (Marketing Oops, 24 Sep 2026): The Big Bang, Snack Jack Ring "Mother Strike"; Multiformat Storytelling, vivo V70.',
      creators: {
        title: 'Creators: luk thung, rap & pop', sub: 'Labels and artists fans replay',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'GMM GRAMMY OFFICIAL', s: '26.1M', x: 'Label', i: 'GMM', url: 'UCG9gfnA5UDoLvz-tC9B-HKw' },
          { n: 'GRAMMY GOLD OFFICIAL', s: '22.3M', x: 'Luk thung', i: 'GG', url: 'UCFWsjsN53Sqvg2pWhSFmWBQ' },
          { n: 'RsiamMusic', s: '20.5M', x: 'Luk thung', i: 'RS', url: 'UCLcCpNY-zaL3vEERD5rh5Ew' },
          { n: 'Genierock', s: '17.3M', x: 'Rock & pop', i: 'GR', url: 'UCs2t9DlvAuyTBkvk2djGZKw' },
          { n: 'welovekamikaze', s: '10.2M', x: 'T-pop', i: 'KZ', url: 'UCjqZeIIXmNj3WS7auJjJFpg' },
          { n: 'LLOUD Official', s: '9.17M', x: 'Pop', i: 'LL', url: 'UC6-BgjsBa5R3PZQ_kZ8hKPg' },
          { n: 'Grammy Big', s: '8.18M', x: 'Hits', i: 'GB', url: 'UC150NxpFj0WLC38uhX8F-Rw' },
          { n: 'Illslick thelegandary', s: '7.4M', x: 'Rap', i: 'IS', url: 'UCPjJUEUwxI7GHMKiiEB-R7w' },
          { n: 'FHERO Official', s: '1.16M', x: '"Kularb"', i: 'FH', url: 'UCpYqAXb3nK7nyZpFiKhWgiQ' },
        ],
      },
      ideas: {
        title: 'Put your brand on the stage',
        cards: [
          { icon: 'PiMicrophoneStageBold', t: 'Rap x luk thung collab', c: 'FHERO Official', d: 'a brand-backed feature track that crosses two fanbases' },
          { icon: 'PiMapPinBold', t: 'Isan road trip session', c: 'RsiamMusic', d: 'artists sing their way home for the festival, with the brand along the route' },
          { icon: 'PiMusicNotesBold', t: 'Dance challenge drop', c: 'welovekamikaze', d: 'a hook built for Shorts, with fans invited to film their own' },
          { icon: 'PiTicketBold', t: 'Festival live stage', c: 'GMM GRAMMY OFFICIAL', d: 'branded stage cuts from Loy Krathong to Songkran' },
        ],
        band: [
          { t: 'Artist feature', d: 'A co-created track or live session with the brand' },
          { t: 'Festival stage', d: 'Stage cuts timed to Loy Krathong and Songkran' },
          { t: 'Fan Shorts boost', d: 'The best fan covers and dance clips, boosted' },
        ],
      },
      inMarket: 'beverages and snacks, mobile and telco, motorbikes and auto, e-wallets and banking',
      lineups: [
        { t: 'VELOTREND: LUK THUNG & MOR LAM', d: 'Trending country and Isan music videos' },
        { t: 'VELOTREND: THAI RAP & POP', d: 'Trending rap, pop and T-pop releases' },
      ],
      what: 'music',
    },
    // ============================================================ 03 GHOST
    {
      key: 'ghost', art: 'ghost', num: '03', name: 'Ghost Stories', tag: '03 · GHOST STORIES',
      short: 'Horror nights, karma tales and ghost hunts', icon: 'PiGhostBold',
      banner: ['PiGhostBold', 'PiMoonStarsBold', 'PiMicrophoneBold', 'PiEyeBold'],
      hero: { topChip: ['Live tonight', 'PiMicrophoneBold'], botChip: ['Listening', 'PiHeadphonesBold'], dur: '1:12:40' },
      divider: { kicker: 'THE THRILL OF', desc: 'Thailand loves a ghost story: live call-in horror shows, karma tales and ghost hunts, watched late into the night.' },
      fact: {
        icon: 'PiGhostBold', big: '2 of 10', lead: 'Two of YouTube Thailand\'s top 10 creators of 2025 tell ghost stories',
        text: 'The Ghost Radio ranked #3 and Lhon Diary #9 on YouTube\'s official list of top creators in Thailand.',
        sowhat: 'Horror is mainstream prime time here, not a niche. It pulls long, late-night viewing sessions brands rarely get.',
        source: 'Source: YouTube Thailand year-end lists, top creators (4 Dec 2025)',
        notes: 'YouTube Thailand top creators 2025 (Google Thailand blog, 4 Dec 2025): 1 MrBeast, 2 OAUJUN HI-END, 3 THE GHOST RADIO, 4 zbing z., 5 SpriteDer SPD, 6 Stokes Twins, 7 Ananped, 8 Noopuynoon, 9 หลอนไดอารี่ (Lhon Diary), 10 Jamsai JS.',
      },
      insight: {
        type: 'stats',
        title: 'Thai horror fills radios, cinemas and screens',
        sub: 'From call-in ghost shows to box office records',
        source: 'Source: Social Blade (Sep 2026); Wikipedia (Death Whisperer 3, Oct 2025); Thairath (8 Dec 2025)',
        stats: [
          { icon: 'PiMicrophoneBold', big: '6.3B', text: 'lifetime views for The Ghost Radio, a call-in ghost story show (8.3M subscribers)' },
          { icon: 'PiFilmSlateBold', big: '฿465M', text: 'for Death Whisperer 3, the strongest Thai film opening in a year' },
          { icon: 'PiTicketBold', big: '฿31.5M', text: 'opening week for "Our House", a film born from a Ghost Radio story' },
        ],
        why: 'ghost stories are watched in long sessions, often with the lights off and on the big screen. A branded episode here holds attention for an hour, not a second.',
      },
      insightNotes: 'The Ghost Radio (TheghostradioOfficial): 8.3M subscribers, 6.3B views, 17,483 videos (Social Blade, Sep 2026).\nDeath Whisperer 3 (ธี่หยด 3), released 1 Oct 2025: ฿465M nationwide; ฿60M opening day, the strongest opening for a Thai film in a year (Wikipedia).\n"Our House", based on a Ghost Radio story series narrated by Khun Nuad: ฿31.5M nationwide in its opening week, 4 to 7 Dec 2025 (Thairath, 8 Dec 2025).',
      working: {
        title: 'Stories told in the dark, watched on repeat',
        source: 'Source: Social Blade (Sep 2026); ATIME official channels (2025); Prachachat (26 Aug 2020)',
        formats: [
          { icon: 'PiPhoneBold', t: 'Call-in ghost shows', d: 'Listeners phone in their own encounters, live' },
          { icon: 'PiBookOpenBold', t: 'Karma & folk tales', d: 'Moral stories told by veteran radio voices' },
          { icon: 'PiFlashlightBold', t: 'Ghost hunts', d: 'Creators spend the night in haunted places' },
          { icon: 'PiHeadphonesBold', t: 'Longplay compilations', d: 'Hour-long story sets for late-night listening' },
        ],
        moments: [
          { d: '31 OCT 2026', t: 'Halloween: the peak horror week' },
          { d: '1ST & 3RD TUESDAY', t: 'ATIME\'s "Angkhan Klum Pong" ghost show, 7 pm' },
          { d: 'Q4 2026', t: 'Thai horror film releases and trailers' },
          { d: 'ALWAYS-ON', t: 'Late-night story drops, every week' },
        ],
      },
      workingNotes: 'ATIME\'s อังคารคลุมโปง Ghostology airs every 1st and 3rd Tuesday of the month at 7 pm on the ATIME Do Dee YouTube channel (ATIME official posts, 2025). Ajarn Yod (อาจารย์ยอด), a former radio host who spent 30+ years on air, tells karma and dharma stories; he was 75 in 2020 (Prachachat, 26 Aug 2020). Epic Time runs ghost-hunting series such as Epic Ghost Camp and Epic Ghost Car.',
      fit: {
        source: 'Source: Social Blade (Sep 2026); Wikipedia (Death Whisperer 3)',
        cats: [
          { icon: 'PiLightningBold', t: 'Energy Drinks & Coffee', d: 'Stay up for one more story' },
          { icon: 'PiCookieBold', t: 'Snacks', d: 'The late-night horror night fuel' },
          { icon: 'PiWifiHighBold', t: 'Telco & Internet', d: 'Keep the story playing all night' },
          { icon: 'PiShieldCheckBold', t: 'Insurance', d: 'Protection, with a wink' },
        ],
        join: [
          { t: 'Host-read segment', d: 'A mention in the host\'s own voice, capped and natural' },
          { t: 'Horror night special', d: 'A branded Halloween horror-night episode' },
          { t: 'Film tie-in', d: 'Stories and ghost hunts around a horror release' },
        ],
      },
      fitNotes: 'Integration guardrail: keep brand mentions in the host\'s own voice and away from the scariest story beats. Horror content should avoid real-tragedy exploitation; brief creators accordingly.',
      creators: {
        title: 'Creators: ghost stories', sub: 'Storytellers, radio shows and ghost hunters',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'Epic Time', s: '8.41M', x: 'Ghost hunts', i: 'ET', url: 'UCUoV88OKSJS8nOun8YY0XWw' },
          { n: 'The Ghost Radio', s: '8.3M', x: 'Call-in stories', i: 'TGR', url: 'UCM246zZ4qNNmFQ2WHnP_CRA' },
          { n: 'Ajarn Yod', s: '7.9M', x: 'Karma tales', i: 'AY', url: 'UCZo5ZB2p-UMqc5e1llZ1RLg (อาจารย์ยอด)' },
          { n: 'Lhon Diary', s: '7.21M', x: 'Horror stories', i: 'LD', url: 'UClxCu8foehDNC8UInjbFKnA (หลอนไดอารี่)' },
          { n: 'The Shock Radio', s: '2.04M', x: 'Radio horror', i: 'TS', url: 'UC8fvuZEXDpKYkgRyR3ihLXg' },
          { n: 'nuenglc', s: '2M', x: 'Horror stories', i: 'NL', url: 'UCUhkMkbH2lL3JKkCjeHGhvw' },
          { n: 'ATIME Do Dee', s: '640K', x: 'Radio ghost show', i: 'AT', url: 'UC_cg0PAWDReL9DZikKvMLGw' },
          { n: 'Lao Pai Lhon Pai', s: '382K', x: 'Horror stories', i: 'LP', url: 'UC_Y4cnyRVn8i3I34Gf-7hpQ (เล่าไปหลอนไป)' },
        ],
      },
      ideas: {
        title: 'Keep them up for one more story',
        cards: [
          { icon: 'PiBroadcastBold', t: 'Sponsored call-in night', c: 'The Ghost Radio', d: 'a live horror night presented by the brand, with listener calls' },
          { icon: 'PiCarBold', t: 'Ghost hunt road trip', c: 'Epic Time', d: 'a night drive to a haunted place, with the car and snacks along for the ride' },
          { icon: 'PiBookOpenBold', t: 'Karma tale series', c: 'Ajarn Yod', d: 'moral stories with a message about care and protection' },
          { icon: 'PiMoonBold', t: 'Halloween longplay', c: 'Lhon Diary', d: 'an hour-long story set for 31 October, presented by the brand' },
        ],
        band: [
          { t: 'Presented-by episode', d: 'The host opens and closes with the brand, in their own voice' },
          { t: 'Halloween special', d: 'A branded horror night timed to 31 October' },
          { t: 'Story Shorts', d: 'The scariest moments cut into Shorts and boosted' },
        ],
      },
      inMarket: 'energy drinks and coffee, snacks, telco and internet, insurance',
      lineups: [
        { t: 'VELOTREND: THAI GHOST STORIES', d: 'Trending horror storytelling and call-in shows' },
        { t: 'LINEUP: HALLOWEEN HORROR', d: 'Horror content around 31 October' },
      ],
      what: 'ghost stories',
    },
    // ============================================================ 04 TALK
    {
      key: 'talk', art: 'talk', num: '04', name: 'Talk of the Town', tag: '04 · TALK OF THE TOWN',
      short: 'Podcasts and talk shows that Gen Z actually finishes', icon: 'PiChatsCircleBold',
      banner: ['PiMicrophoneBold', 'PiChatsCircleBold', 'PiLightbulbBold', 'PiHeadphonesBold'],
      hero: { topChip: ['New episode', 'PiMicrophoneBold'], botChip: ['Watching', 'PiEyeBold'], dur: '1:34:08' },
      divider: { kicker: 'THE VOICE OF', desc: 'Long conversations about business, tech, history and life: Thailand\'s podcasts are watched, not just heard.' },
      fact: {
        icon: 'PiMicrophoneBold', big: '94%', lead: 'of Thai Gen Z say YouTube has the best podcast content',
        text: 'The generation said to have no attention span is the one driving hour-long podcasts on YouTube.',
        sowhat: 'Long-form talk is where young Thais learn, decide and trust. A brand in the conversation gets minutes, not seconds.',
        source: 'Source: Google & Kantar (2026), via The Story Thailand (25 Sep 2026)',
        notes: '94% of Gen Z in Thailand regard YouTube as having the best podcast content (Google & Kantar 2026, presented at YouTube Works Awards Thailand 2026; reported by The Story Thailand and Telecomlover, 25 Sep 2026).',
      },
      insight: {
        type: 'bars',
        title: 'Thailand watches long conversations',
        sub: 'Podcasts and talk channels with loyal audiences',
        chartLabel: 'Subscribers, millions (Social Blade, Sep 2026)',
        bars: [['GoodDayOfficial', 3.95, '3.95M'], ['9arm', 1.61, '1.61M'], ['Mission To The Moon', 1.38, '1.38M'], ['FAROSE', 0.996, '996K'], ['CK Cheong', 0.775, '775K']],
        source: 'Source: Social Blade (Sep 2026); Google via RAiNMaker (18 Jun 2026); Google & Kantar (2026)',
        stats: [
          { big: '+50%', text: 'year-on-year growth in podcast viewing on YouTube Thailand' },
          { big: '87%', text: 'of Thai Gen Z say YouTube helps them make confident purchase decisions' },
          { big: '4,200+', text: 'episodes uploaded by Salmon Podcast since 2019' },
        ],
      },
      insightNotes: 'Subscribers (Social Blade, Sep 2026): GoodDayOfficial 3.95M (1.76B views), 9arm 1.61M, Mission To The Moon 1.38M, FAROSE 996K (plus FAROSE podcast 710K), CK Cheong 775K.\n+50%: podcast viewing grew over 50% in June 2025 vs June 2024 (Google data via RAiNMaker, 18 Jun 2026), which listed Salmon Podcast, GoodDay Podcast, FAROSE, CK Cheong, 9arm, Katanyu Tonight, Koendanai, Long La Bye, Zerosick and The Ghost Radio among notable Thai podcasts.\n87%: Google & Kantar 2026, cited at YouTube Works Awards Thailand 2026.\nSalmon Podcast: 4,212 videos since 19 Aug 2019 (Social Blade).',
      working: {
        title: 'Hour-long talk, watched to the end',
        source: 'Source: Google via RAiNMaker (18 Jun 2026); Social Blade (Sep 2026)',
        formats: [
          { icon: 'PiChatsCircleBold', t: 'Celebrity interviews', d: 'Long, candid talks with stars and newsmakers' },
          { icon: 'PiLightbulbBold', t: 'Explainers', d: 'Tech, business and history made simple' },
          { icon: 'PiCurrencyCircleDollarBold', t: 'Money & career talk', d: 'Investing, careers and running a business' },
          { icon: 'PiFirstAidKitBold', t: 'Health & life', d: 'Doctors and coaches answering real questions' },
        ],
        moments: [
          { d: 'NOV TO DEC 2026', t: 'Year-end tax-saving and investment planning' },
          { d: 'DEC 2026', t: 'Year-in-review episodes' },
          { d: 'JAN 2027', t: 'New Year goals and self-development' },
          { d: 'WEEKLY', t: 'Appointment episodes with loyal audiences' },
        ],
      },
      workingNotes: 'Year-end is when Thai investors buy tax-saving funds (SSF/RMF) before 31 December, a natural moment for banking and investment talk. Formats reflect the podcast list highlighted by Google data via RAiNMaker (Jun 2026).',
      fit: {
        source: 'Source: Google & Kantar (2026); YouTube Works Awards Thailand 2026 winners via Marketing Oops (24 Sep 2026)',
        cats: [
          { icon: 'PiBankBold', t: 'Banking & Investment', d: 'The money conversation, at year-end' },
          { icon: 'PiLaptopBold', t: 'Tech & Devices', d: 'Explainers that settle the big-ticket choice' },
          { icon: 'PiFirstAidKitBold', t: 'Health & Insurance', d: 'Trusted voices on real-life questions' },
          { icon: 'PiSparkleBold', t: 'Beauty & Personal care', d: 'L\'Oreal won Masters of Media 2026' },
        ],
        join: [
          { t: 'Presenting partner', d: 'A season sponsor, mentioned in the host\'s own voice' },
          { t: 'Branded episode', d: 'A conversation built around your theme, not an ad' },
          { t: 'Clips to Shorts', d: 'The best moments cut into Shorts and boosted' },
        ],
      },
      fitNotes: 'This pillar maps directly onto a branded talkshow or vodcast format: host plus guest, capped brand time, mentions in the host\'s own voice. Masters of Media 2026: L\'Oreal Thailand (WPP Media Thailand, Wavemaker).',
      creators: {
        title: 'Creators: podcasts & talk', sub: 'Hosts people listen to for an hour',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'GoodDayOfficial', s: '3.95M', x: 'Talk & variety', i: 'GD', url: 'UC8XqGKvkVgmL_MCs4irRKqw' },
          { n: '9arm', s: '1.61M', x: 'Tech talk', i: '9A', url: 'UCoiEtD4v1qMAqHV5MDI5Qpg' },
          { n: 'Mission To The Moon', s: '1.38M', x: 'Business', i: 'MM', url: 'UC9sGR_RNjzW7vEiTZKj4E_Q' },
          { n: 'FAROSE', s: '996K', x: 'History & stories', i: 'FA', url: 'UC7PFNTtc31iN3hYxghppteA' },
          { n: 'CK Cheong', s: '775K', x: 'Business talk', i: 'CK', url: 'UCON5rTanCDSSTedCwLUbwyg' },
          { n: 'Katanyu Tonight', s: '597K', x: 'Interviews', i: 'KT', url: 'UCSmCGTtoG_cmI7PmQWCQmIA' },
          { n: 'Salmon Podcast', s: '478K', x: 'Culture', i: 'SP', url: 'UCCMOSgTBA_vrUBX_8Iy4JYw' },
          { n: 'Koendanai', s: '450K', x: 'Self-growth', i: 'KD', url: 'UCOg8XhhvNJFHjm4bRh0CZ6w' },
          { n: 'Zerosick', s: '397K', x: 'Health', i: 'ZS', url: 'UCboKYrwUEPD-9gRpuzQDiNA' },
        ],
      },
      ideas: {
        title: 'Join the conversation, not the break',
        cards: [
          { icon: 'PiStarBold', t: 'Celebrity show integration', c: 'Katanyu Tonight', d: 'a star guest interview with a natural, host-led product moment' },
          { icon: 'PiRocketLaunchBold', t: 'Founder stories', c: 'Mission To The Moon', d: 'how a Thai brand was built, told over one long talk' },
          { icon: 'PiCpuBold', t: 'Tech explained', c: '9arm', d: 'the product\'s tech, made simple and honest' },
          { icon: 'PiPiggyBankBold', t: 'Money at year-end', c: 'CK Cheong', d: 'tax, saving and investing talk before 31 December' },
        ],
        band: [
          { t: 'Guest-star episode', d: 'A celebrity sit-down with the brand in the conversation' },
          { t: 'Expert series', d: '3 to 5 episodes on money, tech or health' },
          { t: 'Clips to Shorts', d: 'The best moments cut into Shorts and boosted' },
        ],
      },
      inMarket: 'banking and investment, tech and devices, health and insurance, beauty and personal care',
      lineups: [
        { t: 'VELOTREND: THAI PODCASTS', d: 'Trending podcast and talk episodes' },
        { t: 'VELOTREND: BUSINESS & TECH TALK', d: 'Explainers on money, careers and tech' },
      ],
      what: 'podcasts & talk',
    },
    // ============================================================ 05 EAT & TRAVEL
    {
      key: 'eat', art: 'eat', num: '05', name: 'Eat & Travel Thai', tag: '05 · EAT & TRAVEL THAI',
      short: 'Street food, food trips and local escapes', icon: 'PiBowlFoodBold',
      banner: ['PiBowlFoodBold', 'PiMapPinBold', 'PiForkKnifeBold', 'PiMountainsBold'],
      hero: { topChip: ['Food trip', 'PiMapPinBold'], botChip: ['Saved', 'PiHeartBold'], dur: '24:10' },
      divider: { kicker: 'THE TASTE OF', desc: 'Street food, big bowls and weekend escapes to secondary cities: the trips Thais plan on YouTube.' },
      fact: {
        icon: 'PiMapPinBold', big: '#2', lead: 'Thailand\'s #2 Google search of 2025 was a domestic travel deal',
        text: 'The half-price travel scheme "Thiao Thai Khon La Khrueng" ranked above ChatGPT among the year\'s trending searches.',
        sowhat: 'Thais are hungry to travel at home. The next round opens in October 2026, so brands can ride the planning wave.',
        source: 'Source: Google Year in Search 2025 Thailand (4 Dec 2025), via RAiNMaker',
        notes: 'Google Year in Search 2025 Thailand, top trending searches: 1 Gemini, 2 เที่ยวไทยคนละครึ่ง (half-price domestic travel scheme), 3 ChatGPT, 4 แผ่นดินไหว, 5 คนละครึ่ง พลัส (trends.withgoogle.com and RAiNMaker, Dec 2025). Top domestic destinations: Kamphaeng Phet, Sukhothai, Lampang, Song Wat, Cha-am. The 2026 round (Thai Tiew Thai Plus) opens registration in October 2026 for travel from November 2026 to 28 February 2027 (Thansettakij, 12 Sep 2026).',
      },
      insight: {
        type: 'bars',
        title: 'Thailand eats and travels on YouTube',
        sub: 'Food and travel creators with millions of followers',
        chartLabel: 'Subscribers, millions (Social Blade, Sep 2026)',
        bars: [['BANKII', 10.6, '10.6M'], ['Jack Pap Ho', 9, '9M'], ['Mom Tanad Daek', 4.96, '4.96M'], ['JIMSURIYA V.2', 3.24, '3.24M'], ['Jamsai JS', 2.01, '2.01M']],
        source: 'Source: Social Blade (Sep 2026); ' + YTWA + '; Thansettakij (12 Sep 2026)',
        stats: [
          { big: '75%', text: 'of travel creator Go Went Go\'s views come from the TV screen' },
          { big: '1M', text: 'travel vouchers in the 2026 domestic travel scheme, from November' },
          { big: '#10', text: 'Jamsai JS, a food challenge creator, in YouTube\'s top creators of 2025' },
        ],
      },
      insightNotes: 'Subscribers (Social Blade, Sep 2026): BANKII 10.6M (5.8B views), สวัสดีครับผม แจ็กแปปโฮ (Jack Pap Ho) 9M, หม่อมถนัดแดก (Mom Tanad Daek) 4.96M, JIMSURIYA V.2 3.24M, Jamsai JS 2.01M (3.0B views).\n75%: Go Went Go, cited by Google at YouTube Works Awards Thailand 2026.\n1M: Thai Tiew Thai Plus 2026, 1 million rights, 4B baht budget, registration Oct 2026, use Nov 2026 to 15 Dec 2026 and 16 Jan to 28 Feb 2027 (Thansettakij, 12 Sep 2026).\n#10: YouTube Thailand top creators 2025 (Google, 4 Dec 2025).',
      working: {
        title: 'From street stall to weekend escape',
        source: 'Source: Social Blade (Sep 2026); Kapook (Vegetarian Festival 2026); Thansettakij (12 Sep 2026)',
        formats: [
          { icon: 'PiBowlFoodBold', t: 'Street food hunts', d: 'The best stall in town, found and ranked' },
          { icon: 'PiFireBold', t: 'Food challenges', d: 'Giant portions and spicy tests, built to be shared' },
          { icon: 'PiMapPinBold', t: 'Secondary-city trips', d: 'Weekend escapes beyond the usual destinations' },
          { icon: 'PiCookingPotBold', t: 'Home cooking', d: 'Simple Thai recipes families actually make' },
        ],
        moments: [
          { d: '10 TO 18 OCT 2026', t: 'Vegetarian Festival (Thetsakan Kin Je)' },
          { d: 'NOV 2026 TO FEB 2027', t: 'Domestic travel scheme and high season' },
          { d: '24 NOV 2026', t: 'Loy Krathong trips and night markets' },
          { d: '31 DEC 2026', t: 'New Year trips and countdown feasts' },
        ],
      },
      workingNotes: 'Vegetarian Festival 2569 (2026): 10 to 18 October (Kapook and others). Thai Tiew Thai Plus: usage Nov 2026 to 28 Feb 2027 with a New Year pause (Thansettakij). Loy Krathong: 24 Nov 2026.',
      fit: {
        source: 'Source: YouTube Works Awards Thailand 2026 winners via Marketing Oops (24 Sep 2026); Google (25 Sep 2026)',
        cats: [
          { icon: 'PiDropBold', t: 'Seasoning & Sauces', d: 'The flavour that makes the stall famous' },
          { icon: 'PiCoffeeBold', t: 'Beverages', d: 'The cold drink after the spicy challenge' },
          { icon: 'PiCarBold', t: 'Auto & Travel', d: 'The road trip to the next secondary city' },
          { icon: 'PiCreditCardBold', t: 'Cards & E-wallets', d: 'Pay, earn and redeem on every trip' },
        ],
        join: [
          { t: 'Food trip sponsor', d: 'A branded route through one province' },
          { t: 'Challenge prop', d: 'Your product is the ingredient, prize or drink' },
          { t: 'Commerce link', d: 'Tag the product; Nivea\'s pilot saw 3x online orders' },
        ],
      },
      fitNotes: 'YouTube\'s Commerce Media Network links ads to marketplace checkout; Nivea Thailand\'s pilot saw online orders triple and offline sales rise 32% (Google, YouTube Works Awards Thailand 2026, via Telecomlover, 25 Sep 2026).',
      creators: {
        title: 'Creators: eat & travel', sub: 'Food hunters and weekend explorers',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'BANKII', s: '10.6M', x: 'Food challenges', i: 'BK', url: 'UCTHA9ZB9vGvERvgBh-fsHQA' },
          { n: 'Jack Pap Ho', s: '9M', x: 'Food & travel', i: 'JP', url: 'UCUfnk5CgUjykoc-BezLMMIA (สวัสดีครับผม แจ็กแปปโฮ)' },
          { n: 'Mom Tanad Daek', s: '4.96M', x: 'Food reviews', i: 'MT', url: 'UC_iF8sFFnZDDcqe9VnSzyRA (หม่อมถนัดแดก)' },
          { n: 'JIMSURIYA V.2', s: '3.24M', x: 'Cooking', i: 'JS', url: 'UCUpWU-ZHdlJaOAp0S3Rktew' },
          { n: 'Jamsai JS', s: '2.01M', x: 'Food challenges', i: 'JJ', url: 'UCSZYkeZSO6ZHJRBS_G4UYLg' },
          { n: 'Go Went Go', s: '1.97M', x: 'Travel', i: 'GW', url: 'UCqs3pijNrYHZCdl_HGfgTQw' },
          { n: 'TheGaijinTrips', s: '1.26M', x: 'Backpacking', i: 'TG', url: 'UCweR4gGVYrvxGDG7HKIdRZA' },
          { n: 'Starvingtime', s: '446K', x: 'Food finds', i: 'ST', url: 'UCEPwlU59eA7jJ_wS2jr1RVQ' },
        ],
      },
      ideas: {
        title: 'Make your product part of the trip',
        cards: [
          { icon: 'PiMapTrifoldBold', t: 'Secondary-city food trail', c: 'Jack Pap Ho', d: 'one province, ten stalls, with the brand along for the ride' },
          { icon: 'PiForkKnifeBold', t: 'Honest taste test', c: 'Mom Tanad Daek', d: 'a blind review that settles which one tastes best' },
          { icon: 'PiLeafBold', t: 'Kin Je special', c: 'JIMSURIYA V.2', d: 'vegetarian festival recipes, cooked with the brand\'s product' },
          { icon: 'PiAirplaneTiltBold', t: 'Budget trip plan', c: 'Go Went Go', d: 'a travel-scheme weekend that shows how to save and spend' },
        ],
        band: [
          { t: 'Branded route', d: 'A multi-episode trip through one province' },
          { t: 'Hero ingredient', d: 'The product at the center of the dish' },
          { t: 'Tag and shop', d: 'Product tags that turn the trip into a cart' },
        ],
      },
      inMarket: 'seasoning and sauces, beverages, auto and travel, cards and e-wallets',
      lineups: [
        { t: 'VELOTREND: THAI FOOD & STREET EATS', d: 'Trending food reviews and challenges' },
        { t: 'VELOTREND: THAI TRAVEL', d: 'Trending domestic trips and travel vlogs' },
      ],
      what: 'eat & travel',
    },
    // ============================================================ 06 GAME ON
    {
      key: 'game', art: 'game', num: '06', name: 'Game On', tag: '06 · GAME ON',
      short: 'Gaming creators and RoV nights for the whole family', icon: 'PiGameControllerBold',
      banner: ['PiGameControllerBold', 'PiTrophyBold', 'PiSwordBold', 'PiLightningBold'],
      hero: { topChip: ['Live', 'PiBroadcastBold'], botChip: ['Victory', 'PiTrophyBold'], dur: 'LIVE', durRed: true },
      divider: { kicker: 'THE RUSH OF', desc: 'Gaming creators are some of Thailand\'s biggest stars, and RoV nights fill living rooms.' },
      fact: {
        icon: 'PiGameControllerBold', big: '22M', lead: 'A single Thai gamer has more YouTube subscribers than a national TV channel',
        text: 'zbing z. (22M) out-subscribes Ch7HD (19.7M) and ranks #7 in the whole country.',
        sowhat: 'Gaming creators have broadcast-scale reach with far deeper fan loyalty. They are TV channels in their own right.',
        source: 'Source: Social Blade (Sep 2026); YouTube Thailand top creators (4 Dec 2025)',
        notes: 'Social Blade (Sep 2026): zbing z. 22M subscribers, Thailand rank #7, 13.2B views; Ch7HD 19.7M. YouTube named zbing z. #4 in its top creators of 2025 in Thailand, "the icon of Thai gaming broadcast" (Google, 4 Dec 2025).',
      },
      insight: {
        type: 'stats',
        title: 'Thailand plays together, on the big screen',
        sub: 'Gaming creators and esports with national reach',
        source: 'Source: HypeAuditor Thailand ranking (Sep 2026); Esports Charts (2026); Thailand Game Show (2026)',
        stats: [
          { icon: 'PiUsersThreeBold', big: '7 of 50', text: 'of Thailand\'s most-subscribed YouTube channels are gaming channels' },
          { icon: 'PiBroadcastBold', big: '122K', text: 'peak viewers for RoV Pro League 2026 Summer' },
          { icon: 'PiCalendarStarBold', big: '4 days', text: 'of Thailand Game Show in Bangkok, 29 Oct to 1 Nov 2026' },
        ],
        why: 'gaming here is family entertainment: long Let\'s Plays, RoV nights and live streams, watched together and replayed on demand.',
      },
      insightNotes: 'HypeAuditor top 50 Thailand (Sep 2026): zbing z., Bie The Ska, HEARTROCKER, PojzPlaza, PRIMKUNG, 1412 CH and LowGrade are gaming channels (7 of 50).\nRoV Pro League 2026 Summer: 122K peak viewers (Esports Charts). RoV Pro League 2026 Winter runs 22 Aug to 1 Oct 2026.\nThailand Game Show 2026 (co-branded with gamescom): 29 Oct to 1 Nov 2026, QSNCC Bangkok.\nBrand safety: Bie The Ska was not shortlisted (2023 parody backlash); 1412 CH was excluded (low views relative to subscribers).',
      working: {
        title: 'Play, watch, replay',
        source: 'Source: Esports Charts (2026); Thailand Game Show (2026)',
        formats: [
          { icon: 'PiGameControllerBold', t: 'Let\'s Plays', d: 'Roblox, Minecraft and new releases with personality' },
          { icon: 'PiSwordBold', t: 'RoV & Free Fire', d: 'Mobile battles, guides and ranked climbs' },
          { icon: 'PiBroadcastBold', t: 'Live streams', d: 'Community nights with chat and challenges' },
          { icon: 'PiTrophyBold', t: 'Esports broadcasts', d: 'League matches, highlights and finals' },
        ],
        moments: [
          { d: 'TO 1 OCT 2026', t: 'RoV Pro League 2026 Winter finals' },
          { d: '29 OCT TO 1 NOV', t: 'Thailand Game Show, Bangkok' },
          { d: 'OCT & MAR TO MAY', t: 'School holidays: peak gaming time' },
          { d: '9 JAN 2027', t: 'Children\'s Day: family gaming moments' },
        ],
      },
      workingNotes: 'RoV Pro League 2026 Winter: 22 Aug to 1 Oct 2026 (Esports Charts). Thailand Game Show 2026 (co-branded with gamescom): 29 Oct to 1 Nov 2026 at QSNCC. Thai school breaks run roughly October and March to May. Children\'s Day is the second Saturday of January (9 Jan 2027).',
      fit: {
        source: 'Source: YouTube Works Awards Thailand 2026 winners via Marketing Oops (24 Sep 2026)',
        cats: [
          { icon: 'PiDeviceMobileBold', t: 'Mobile & Telco', d: 'Lag-free data for every ranked match' },
          { icon: 'PiCookieBold', t: 'Snacks & Drinks', d: 'Snack Jack won The Big Bang 2026' },
          { icon: 'PiLaptopBold', t: 'Gaming Gear', d: 'Phones, laptops and headsets that keep up' },
          { icon: 'PiWalletBold', t: 'E-wallets & Top-ups', d: 'Top up in-game, pay in one tap' },
        ],
        join: [
          { t: 'Creator challenge', d: 'A branded game night or in-game quest' },
          { t: 'Tournament partner', d: 'Own a community cup or league segment' },
          { t: 'Highlights Roadblock', d: 'Own the replays after every big match' },
        ],
      },
      fitNotes: 'Many Thai gaming channels have family audiences; keep integrations age-appropriate and avoid products restricted for minors.',
      creators: {
        title: 'Creators: gaming & esports', sub: 'Gamers, streamers and leagues',
        source: 'Source: Social Blade (Sep 2026)',
        list: [
          { n: 'zbing z.', s: '22M', x: 'Gaming', i: 'ZZ', url: 'UC5zGJZpxeZPFcds5gFcDE7Q' },
          { n: 'RUOK', s: '10.7M', x: 'Free Fire', i: 'RU', url: 'UC9FL0_4gUAQJLVmlExjx1Xw' },
          { n: 'HEARTROCKER', s: '9.67M', x: 'Gaming', i: 'HR', url: 'UC4plRabXFGdAE6HP-tBQKdQ' },
          { n: 'PojzPlaza', s: '9.63M', x: 'Family gaming', i: 'PP', url: 'UCzyeq_iKmrFTBQ0kzNSqMtg' },
          { n: 'PRIMKUNG', s: '8.72M', x: 'Family gaming', i: 'PK', url: 'UChjKDMnMMG6iZY3twuuS2zg' },
          { n: 'LowGrade', s: '8.29M', x: 'Gaming', i: 'LG', url: 'UCycKzia69PXRbk0N0I9n4Aw' },
          { n: 'Garena Free Fire TH', s: '5.67M', x: 'Official', i: 'FF', url: 'UCe5H8YhDjg_441KjjS5qrAg' },
          { n: 'Garena RoV Thailand', s: '3.9M', x: 'Esports', i: 'ROV', url: 'UCy19QXxbCHh8qVVCbuGk-ig' },
        ],
      },
      ideas: {
        title: 'Join the game, not just the break',
        cards: [
          { icon: 'PiGameControllerBold', t: 'Branded game night', c: 'zbing z.', d: 'a live community night with a product-powered challenge' },
          { icon: 'PiUsersThreeBold', t: 'Squad quest', c: 'RUOK', d: 'a mobile battle series where the brand sets the mission' },
          { icon: 'PiTrophyBold', t: 'League finals segment', c: 'Garena RoV Thailand', d: 'a branded moment inside the finals broadcast and highlights' },
          { icon: 'PiDesktopTowerBold', t: 'Setup makeover', c: 'LowGrade', d: 'a gear and connection upgrade, reviewed on stream' },
        ],
        band: [
          { t: 'Live segment', d: 'A recurring branded moment inside the stream' },
          { t: 'Community cup', d: 'A creator tournament co-hosted by the brand' },
          { t: 'Clips to ads', d: 'The best live moments cut and boosted' },
        ],
      },
      inMarket: 'mobile and telco, snacks and drinks, gaming gear, e-wallets and top-ups',
      lineups: [
        { t: 'VELOTREND: THAI GAMING', d: 'Trending Let\'s Plays and gaming creators' },
        { t: 'VELOTREND: RoV & MOBILE ESPORTS', d: 'League matches, highlights and guides' },
      ],
      what: 'gaming & esports',
    },
  ],
  sources: [
    'Google / YouTube Works Awards Thailand 2026: The Story Thailand and Telecomlover (25 Sep 2026); Marketing Oops winners (24 Sep 2026); Google & Kantar (2026)',
    'Google Thailand blog: Year in Search 2025 (4 Dec 2025) and YouTube year-end lists 2025 (4 Dec 2025); RAiNMaker (Dec 2025; 18 Jun 2026)',
    'Bangkok Post (2025), YouTube creator economy report; Analytic Edge MMM meta-analysis 2021-2025; Nielsen (23 Oct 2024)',
    'Nation Thailand (11 Jan 2025, YouTube Charts 2024; 5 Jun 2026, BL/GL industry); The Geekiary (Nov 2025, GMMTV 2026 lineup)',
    'Wikipedia: Death Whisperer 3; Thairath (8 Dec 2025, "Our House"); Prachachat (26 Aug 2020, Ajarn Yod); ATIME official posts (2025)',
    'Esports Charts (RoV Pro League 2026); Thailand Game Show (2026); HypeAuditor Thailand ranking (Sep 2026)',
    'ChaPop (29 Jul 2026, Big Mountain); Thansettakij (12 Sep 2026, Thai Tiew Thai Plus); Kapook (Vegetarian Festival 2026); Loy Krathong 2026 date guides',
    'Subscriber counts: Social Blade (Sep 2026). Creators screened for brand safety; channel IDs in speaker notes',
  ],
};
